-- Inserimento delle disabilità in inglese
INSERT INTO accountcategories (description) VALUES
('Paralysis (paraplegia)'),
('Paralysis (tetraplegia)'),
('Paralysis (hemiplegia)'),
('Paresis'),
('Amputations'),
('Muscular dystrophy'),
('Multiple sclerosis (in some cases)'),
('Cerebral palsy (CP)'),
('Spina bifida'),
('Spinal cord injuries'),
('Rheumatic diseases'),
('Congenital limb malformations'),
('Ataxia'),
('Chorea'),
('Tremor'),
('Tourette syndrome (movement-related)'),
('Dyskinesia'),
('Lactose intolerance'),
('Gluten intolerance (celiac disease)'),
('Fructose intolerance'),
('Multiple chemical sensitivity (MCS)'),
('Total blindness'),
('Severe low vision'),
('Advanced glaucoma'),
('Retinitis pigmentosa'),
('Macular degeneration'),
('Total deafness'),
('Hearing loss'),
('Deaf-mutism'),
('Touch, smell, taste disorders'),
('Chronic kidney disease'),
('Chronic respiratory failure'),
('COPD'),
('Cystic fibrosis'),
('Severe cardiovascular diseases'),
('Heart failure'),
('Complex congenital heart diseases'),
('Diabetes mellitus with severe complications'),
('Chronic liver diseases'),
('Chronic inflammatory bowel diseases'),
('Fibromyalgia and chronic fatigue syndrome'),
('Intellectual disability'),
('Down syndrome'),
('Williams syndrome'),
('Fragile X syndrome'),
('Other genetic syndromes'),
('Autism spectrum disorders'),
('Schizophrenia and other psychotic disorders'),
('Major depression'),
('Bipolar disorder'),
('Obsessive-compulsive disorder (OCD)'),
('Panic disorder'),
('Generalized anxiety disorder (GAD)'),
('Severe phobias'),
('Personality disorders'),
('Attention deficit hyperactivity disorder (ADHD)'),
('Post-traumatic stress disorder (PTSD)'),
('Anorexia nervosa'),
('Bulimia nervosa'),
('Dyslexia'),
('Dysgraphia'),
('Dysorthographia'),
('Dyscalculia'),
('Non-verbal learning disability (NVLD)'),
('Rare diseases'),
('Chronic disabling conditions'),
('Multiple disabilities');