-- Inserimento delle disabilità fisiche legate al movimento o intolleranza
INSERT INTO accountcategories (description) VALUES
('Paralisi (paraplegia)'),
('Paralisi (tetraplegia)'),
('Paralisi (emiplegia)'),
('Paresi'),
('Amputazioni'),
('Distrofia muscolare'),
('Sclerosi multipla (in alcuni casi)'),
('Paralisi cerebrale infantile (PCI)'),
('Spina bifida'),
('Lesioni del midollo spinale'),
('Malattie reumatiche'),
('Malformazioni congenite degli arti'),
('Atassia'),
('Corea'),
('Tremore'),
('Sindrome di Tourette (movimento)'),
('Discinesia'),
('Intolleranza al lattosio'),
('Intolleranza al glutine (celiachia)'),
('Intolleranza al fruttosio'),
('Ipersensibilità chimica multipla (MCS)'),
('Cecità totale'),
('Ipovisione grave'),
('Glaucoma avanzato'),
('Retinite pigmentosa'),
('Maculopatia degenerativa'),
('Sordità totale'),
('Ipoacusia'),
('Sordomutismo'),
('Tatto, olfatto, gusto'),
('Insufficienza renale cronica'),
('Insufficienza respiratoria cronica'),
('BPCO'),
('Fibrosi cistica'),
('Malattie cardiovascolari gravi'),
('Insufficienza cardiaca'),
('Cardiopatie congenite complesse'),
('Diabete mellito con gravi complicanze'),
('Malattie epatiche croniche'),
('Malattie infiammatorie croniche intestinali'),
('Fibromialgia e sindrome da stanchezza cronica'),
('Ritardo mentale'),
('Sindrome di Down'),
('Sindrome di Williams'),
('Sindrome di Fragile X'),
('Altre sindromi genetiche'),
('Disturbi dello spettro autistico'),
('Schizofrenia e altri disturbi psicotici'),
('Disturbi dell\'umore - Depressione maggiore'),
('Disturbi dell\'umore - Disturbo bipolare'),
('Disturbi d\'ansia - Disturbo ossessivo-compulsivo (DOC)'),
('Disturbi d\'ansia - Disturbo da attacchi di panico'),
('Disturbi d\'ansia - Disturbo d\'ansia generalizzato (DAG)'),
('Disturbi d\'ansia - Fobie gravi'),
('Disturbi di personalità'),
('Disturbo da deficit di attenzione e iperattività (ADHD)'),
('Disturbo post-traumatico da stress (PTSD)'),
('Disturbi del comportamento alimentare - Anoressia nervosa'),
('Disturbi del comportamento alimentare - Bulimia nervosa'),
('Dislessia'),
('Disgrafia'),
('Disortografia'),
('Discalculia'),
('Disturbo specifico dell\'apprendimento non verbale (DSA-NVLD)'),
('Malattie rare'),
('Condizioni croniche invalidanti'),
('Pluridisabilità');
